# Generated by Django 5.2.8 on 2025-11-27 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageVisit',
            new_name='Visit',
        ),
    ]
